[project]
site_name = "lumikeiju.dev"
site_description = "Lumikeiju's main personal website."
site_author = "Lumikeiju"
site_url = "https://lumikeiju.dev/"
repo_name = "lumikeiju.dev"
repo_url = "https://github.com/lumikeiju/lumikeiju.github.io/"
copyright = "Copyright &copy; Lumikeiju"
# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]
use_directory_urls = true

[project.theme]
# custom_dir = "overrides"
favicon = "images/favicon.png"
language = "en"
# logo = "resources/images/logo.png"
features = [
    # "announce.dismiss",
    # "content.action.edit",
    # "content.action.view",
    # "content.code.annotate",
    # "content.code.copy",
    # "content.code.select",
    # "content.footnote.tooltips",
    # "content.tabs.link",
    # "content.tooltips",
    # "header.autohide",
    # "navigation.expand",
    # "navigation.footer",
    # "navigation.indexes",
    # "navigation.instant",
    # "navigation.instant.prefetch",
    # "navigation.instant.progress",
    # "navigation.path",
    # "navigation.prune",
    # "navigation.sections",
    # "navigation.tabs",
    # "navigation.tabs.sticky",
    # "navigation.top",
    # "navigation.tracking",
    # "search.highlight",
    # "toc.follow",
    # "toc.integrate",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.theme.font]
text = "Atkinson Hyperlegible Mono"
code = "Atkinson Hyperlegible Mono"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.validation]
unresolved_references = true
unresolved_footnotes = true
unused_definitions = true
unused_footnotes = true
shadowed_definitions = true
shadowed_footnotes = true
invalid_links = true
invalid_link_anchors = true
